ARG NODE_VERSION=21-alpine3.18

FROM node:${NODE_VERSION} as builder
USER node
WORKDIR /app
COPY . .
RUN npm
RUN npm build

FROM node:${NODE_VERSION}
USER node
WORKDIR /app
COPY . .
COPY --from=builder /app .

EXPOSE 3000
CMD ["sh", "-c", "npm migrate && npm start"]